doctrine:
    dbal:
        #server_version: '13'
        dbname: test
        host: 172.42.0.20
        port: 3306
        user: root
        password: strongpassword

when@prod:
    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
